services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9997

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  iot-simulator:
    build:
      context: .
      dockerfile: iot-simulator/Dockerfile
    container_name: iot-simulator
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    restart: on-failure

  alert-selector:
   build:
     context: .
     dockerfile: alert-selector/Dockerfile
   container_name: alert-selector
   depends_on:
     - kafka
     - iot-simulator
   environment:
     KAFKA_BOOTSTRAP_SERVERS: kafka:29092
   restart: on-failure

  alert-handler:
   build:
     context: .
     dockerfile: alert-handler/Dockerfile
   container_name: alert-handler
   depends_on:
     - kafka
     - alert-selector
   environment:
     KAFKA_BOOTSTRAP_SERVERS: kafka:29092
   restart: on-failure

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - "3001:3001"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-worldmap-panel,grafana-piechart-panel
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: on-failure

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-storage:/data
    command: server /data --console-address ":9001"
    restart: on-failure
  
  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb local/iot-events;
      mc policy set public local/iot-events;
      exit 0;
      "

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: adminadmin        # same as <USERNAME>
      DOCKER_INFLUXDB_INIT_PASSWORD: adminadmin        # same as <PASSWORD>
      DOCKER_INFLUXDB_INIT_ORG: iot-org                # same as <ORG_NAME>
      DOCKER_INFLUXDB_INIT_BUCKET: iot-analytics       # same as <BUCKET_NAME>
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-token # recommended to set
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    restart: on-failure


  # service-analytics:
  #   build:
  #     context: ./service-analytics
  #     dockerfile: Dockerfile
  #   container_name: service-analytics
  #   depends_on:
  #     - kafka
  #     - minio
  #     - influxdb
  #     - grafana
  #   environment:
  #     MINIO_ENDPOINT: http://minio:9000
  #     MINIO_ACCESS_KEY: minioadmin
  #     MINIO_SECRET_KEY: minioadmin
  #     MINIO_BUCKET: iot-events
  #     INFLUXDB_URL: http://influxdb:8086
  #     INFLUXDB_TOKEN: admin-token
  #     INFLUXDB_ORG: iot-org
  #     INFLUXDB_BUCKET: iot-analytics
  #     GRAFANA_URL: http://grafana:3000
  #     GRAFANA_API_KEY: admin
  #   restart: on-failure

volumes:
  grafana-storage:
    driver: local
  minio-storage:
    driver: local
  influxdb:
    driver: local
